spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: user
    password: user
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
hibernate:
  hbm2ddl:
    auto: none
  dialect: org.hibernate.dialect.PostgreSQL10Dialect
